#
# This will copy the app src and compile a binary and save it as /go/bin/app
#

FROM golang:1.7

RUN mkdir -p /go/src/app
WORKDIR /go/src/app

ARG CGO_LDFLAGS
ARG GOOS

CMD ["go-wrapper", "run"]

COPY src/github.com/issuu/pipe2log/. /go/src/app
RUN go-wrapper download
RUN env GOOS=${GOOS} go-wrapper install -ldflags "${CGO_LDFLAGS}"

